# -*- coding: utf-8 -*-
"""News fetcher.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/156OCiUtZRVDtRA69s9P6uGDWkOyUo-AP
"""

pip install newsapi-python

from newsapi import NewsApiClient

# Initialize the News API client with your API key
newsapi = NewsApiClient(api_key='8c0dc9532fa04e85b97fd2ee9fdbdb1e')

def fetch_news(query, language='en', page_size=5):
    try:
        # Fetch news articles
        response = newsapi.get_everything(q=query, language=language, page_size=page_size)

        # Check if articles are found
        if response['status'] == 'ok' and response['totalResults'] > 0:
            articles = response['articles']
            news_list = []

            # Process and print each article's title and link
            for article in articles:
                title = article['title']
                url = article['url']
                news_list.append(f"{title}\n{url}\n")

            return news_list
        else:
            return "No news articles found."

    except Exception as e:
        return f"An error occurred: {str(e)}"

# Fetch news based on a query
query = "technology"
news = fetch_news(query)
for item in news:
    print(item)